<!--Location Map-->
<?php $this->headLink()->appendStylesheet($this->basePath('/css/map_style.css'));?>
<section>
    <div id="form_div">
    <div class="row">
        <div class="span12">
            <!--<div class="col-xs-3">-->
                <div id="map_inputs">
                    <!--<legend><strong>Search & Save</strong></legend>-->
                    <p>
        <!--            <label for="search_new_places">New Places</label>-->
                    <input type="text" placeholder="Search New Places" id="search_new_places" autofocus class="form-control">
                    </p>
                    <p>
                    <!--<label for="search_ex_places">Saved Places</label>-->
                    <input type="text" placeholder="Search Saved Places" id="search_ex_places" list="saved_places" class="form-control">
                    </p>
                    <input type="hidden" name="place_id" id="place_id"/>
                    <p>
                    <!--<label for="place">Name</label>-->
                    <input type="text" placeholder="Name Your Place" name="n_place" id="n_place" class="form-control"/>
                    </p>
                    <p>
                    <!--<label for="description">Description</label>-->
                    <input type="text" placeholder="Description" name="n_description" id="n_description" class="form-control"/>
                    </p>

                    <p>
                        <input type="button" id="plot_marker" value="plot marker" class="btn btn-success btn-sm"/>
                        <input type="button" id="btn_save" value="save place" class="btn btn-primary btn-sm"/>
                    </p>
                </div>
            <!--</div>-->
            <!--<div class="col-xs-9">-->
                <div id="map_container">
                    <!--style="width:1100px; height: 600px;"-->
                    <div id="map_canvas"></div>
                </div>
            <!--</div>-->
        </div>
    </div>
    <datalist id="saved_places">
    <!--loop through the places saved in the database and store their data into each of the data attribute in the options-->
    <?php//$places = $db->query("SELECT * FROM map_places");?>
    <?php // while($row = $places->fetch_object()){ ?>
    <!--<option value="<?php // echo $row->place; ?>" data-id="<?php // echo $row->place_id; ?>" data-lat="<?php // echo $row->lat; ?>" data-lng="<?php // echo $row->lng; ?>" data-place="<?php // echo $row->place; ?>" data-description="<?php // echo $row->description; ?>"><?php // echo $row->place; ?></option>-->
    <?php // } ?>
    </datalist>
        <!--Include the googleapi script and the functionality in map.js-->
        <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyD9uiyFbXfbSOsY6umTUtl4_rvl_LkQKxE&sensor=false&libraries=places"></script>
        <script type="text/javascript" src="../js/map.js"></script>
    </div>
</section>
<?php // $this->headScript()->appendFile($this->basePath('js/map.js')) // appending or prepending Cannot work in this case;?>
