<?php // 
    $applicant = $this->form;
//    $url = $this->url('data', array('action' => 'edit', 'id' => $id));
//    $form->setAttribute('action', $url);
//    $form->get('submit')->setAttribute('value', 'Edit');
    $applicant->prepare(); 
    echo $this->form()->openTag($applicant); 
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <form class="form-horizontal">
                <div class="form-group">
                    <fieldset>
                        <legend>User details</legend>
                        <div class="col-xs-8">
                            <div class="row">
                                <label class="control-label col-xs-3"><?php echo $this->formlabel($applicant->get('name')); ?></label>
                                <div class="col-xs-9"><?php echo $this->forminput($applicant->get('name')->setAttribute('class','form-control')); ?></div>
                            </div><br/>
                            <?php echo $this->formHidden($form->get('security')); ?>
                        </br>
                        <?php echo $this->formInput($form->get('submit')->setAttribute('class',"btn btn-primary")); ?>
                        </div>
                        <div class="col-xs-1"><!--column for space between fields and picture-->

                        </div>
                        <div class="col-xs-3">
                                <img src="../img/test.jpg" class="img-responsive img-rounded" style="width:150px; height:200px;"></img>
                                <img src="../img/sign.jpg" class="img-responsive img-rounded" style="width:150px; height:100px;"></img>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag($applicant); ?>

<!--MODAL DIALOG DISPLAY - An example of form display in lightbox from http://jqueryui.com/dialog/#modal-form-->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <!--<script src="//code.jquery.com/jquery-1.10.2.js"></script>-->
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <style>
    /*body { font-size: 62.5%; }*/
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
  <script>
  $(function() {
    var dialog, form,
 
      // From http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#e-mail-state-%28type=email%29
      emailRegex = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/,
      name = $( "#name" ),
      email = $( "#email" ),
      password = $( "#password" ),
      allFields = $( [] ).add( name ).add( email ).add( password ),
      tips = $( ".validateTips" );
 
    function updateTips( t ) {
      tips
        .text( t )
        .addClass( "ui-state-highlight" );
      setTimeout(function() {
        tips.removeClass( "ui-state-highlight", 1500 );
      }, 500 );
    }
 
    function checkLength( o, n, min, max ) {
      if ( o.val().length > max || o.val().length < min ) {
        o.addClass( "ui-state-error" );
        updateTips( "Length of " + n + " must be between " +
          min + " and " + max + "." );
        return false;
      } else {
        return true;
      }
    }
 
    function checkRegexp( o, regexp, n ) {
      if ( !( regexp.test( o.val() ) ) ) {
        o.addClass( "ui-state-error" );
        updateTips( n );
        return false;
      } else {
        return true;
      }
    }
 
    function addUser() {
      var valid = true;
      allFields.removeClass( "ui-state-error" );
 
      valid = valid && checkLength( name, "username", 3, 16 );
      valid = valid && checkLength( email, "email", 6, 80 );
      valid = valid && checkLength( password, "password", 5, 16 );
 
      valid = valid && checkRegexp( name, /^[a-z]([0-9a-z_\s])+$/i, "Username may consist of a-z, 0-9, underscores, spaces and must begin with a letter." );
      valid = valid && checkRegexp( email, emailRegex, "eg. ui@jquery.com" );
      valid = valid && checkRegexp( password, /^([0-9a-zA-Z])+$/, "Password field only allow : a-z 0-9" );
 
      if ( valid ) {
        $( "#users tbody" ).append( "<tr>" +
          "<td>" + name.val() + "</td>" +
          "<td>" + email.val() + "</td>" +
          "<td>" + password.val() + "</td>" +
        "</tr>" );
        dialog.dialog( "close" );
      }
      return valid;
    }
 
    dialog = $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 400,
      width: 450,
      modal: true,
      buttons: {
        "Create an account": addUser,
        Cancel: function() {
          dialog.dialog( "close" );
        }
      },
      close: function() {
        form[ 0 ].reset();
        allFields.removeClass( "ui-state-error" );
      }
    });
 
    form = dialog.find( "form" ).on( "submit", function( event ) {
      event.preventDefault();
      addUser();
    });
 
    $( "#create-user" ).button().on( "click", function() {
      dialog.dialog( "open" );
    });
  });
  </script>
 
<div id="dialog-form" title="Create new user">
  <p class="validateTips">All form fields are required.</p>
 
  <form>
    <fieldset>
      <label for="name">Name</label>
      <input type="text" name="name" id="name" value="Jane Smith" class="text ui-widget-content ui-corner-all">
      <label for="email">Email</label>
      <input type="text" name="email" id="email" value="jane@smith.com" class="text ui-widget-content ui-corner-all">
      <label for="password">Password</label>
      <input type="password" name="password" id="password" value="xxxxxxx" class="text ui-widget-content ui-corner-all">
 
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
  <!--Location Map-->
<?php $this->headLink()->appendStylesheet($this->basePath('/css/map_style.css'));?>
<section>
    <div id="form_div">
    <div class="row">
        <div class="span12">
            <!--<div class="col-xs-3">-->
                <div id="map_inputs">
                    <!--<legend><strong>Search & Save</strong></legend>-->
                    <p>
        <!--            <label for="search_new_places">New Places</label>-->
                    <input type="text" placeholder="Search New Places" id="search_new_places" autofocus class="form-control">
                    </p>
                    <p>
                    <!--<label for="search_ex_places">Saved Places</label>-->
                    <input type="text" placeholder="Search Saved Places" id="search_ex_places" list="saved_places" class="form-control">
                    </p>
                    <input type="hidden" name="place_id" id="place_id"/>
                    <p>
                    <!--<label for="place">Name</label>-->
                    <input type="text" placeholder="Name Your Place" name="n_place" id="n_place" class="form-control"/>
                    </p>
                    <p>
                    <!--<label for="description">Description</label>-->
                    <input type="text" placeholder="Description" name="n_description" id="n_description" class="form-control"/>
                    </p>

                    <p>
                        <input type="button" id="plot_marker" value="plot marker" class="btn btn-success btn-sm"/>
                        <input type="button" id="btn_save" value="save place" class="btn btn-primary btn-sm"/>
                    </p>
                </div>
            <!--</div>-->
            <!--<div class="col-xs-9">-->
                <div id="map_container">
                    <!--style="width:1100px; height: 600px;"-->
                    <div id="map_canvas"></div>
                </div>
            <!--</div>-->
        </div>
    </div>
    <datalist id="saved_places">
    <!--loop through the places saved in the database and store their data into each of the data attribute in the options-->
    <?php//$places = $db->query("SELECT * FROM map_places");?>
    <?php // while($row = $places->fetch_object()){ ?>
    <!--<option value="<?php // echo $row->place; ?>" data-id="<?php // echo $row->place_id; ?>" data-lat="<?php // echo $row->lat; ?>" data-lng="<?php // echo $row->lng; ?>" data-place="<?php // echo $row->place; ?>" data-description="<?php // echo $row->description; ?>"><?php // echo $row->place; ?></option>-->
    <?php // } ?>
    </datalist>
        <!--Include the googleapi script and the functionality in map.js-->
        <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyD9uiyFbXfbSOsY6umTUtl4_rvl_LkQKxE&sensor=false&libraries=places"></script>
        <script type="text/javascript" src="../js/map.js"></script>
    </div>
</section>
<?php // $this->headScript()->appendFile($this->basePath('js/map.js')) // appending or prepending Cannot work in this case;?>

</div>
 
<button id="create-user">Create new user</button>
 