<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-5 col-xs-6">
        <div class="zend_form">
            <br/>
            <?php echo $this->formElementErrors($form->get('identity')) ?>
            <?php echo $this->formLabel($form->get('identity')) ?>
            <?php echo $this->formInput($form->get('identity')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Your email address')) ?>
            <br/>
            <?php echo $this->formLabel($form->get('credential')) ?>
            <?php echo $this->formInput($form->get('credential')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Your password')) ?>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
            <br/>
            <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
            <br/>
            <br/>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>



