<?php
//    $this->layout('layout.phtml');
    $title = 'Add new exam';
    $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('data', array('action' => 'add')));
 $form->get('submit')->setAttribute('value', 'Add');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('exam_id'));
 echo $this->formRow($form->get('examname')->setAttribute('class', 'form-control'));
 ?>
 <div>
     <br /> 
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);